name: Publish Docker Image

#on: [workflow_dispatch]
on:
  pull_request:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: ami-iit/human-base-estimation-docker
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: dockerfiles
          context: dockerfiles/../
          registry: ghcr.io
